import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import type { RoomPermission, RoomRole } from "@/lib/room-api";

export type RealtimeRoomCredentials = { code: string; serverUrl: string; token: string };
type PreviewMessage = { id: string; authorName: string; text: string; mine: boolean };

export function RoomRealtimePanel({ callVolume: _callVolume, onCallVolumeChange: _onCallVolumeChange, onSelfAccessChange: _onSelfAccessChange, participantId: _participantId, permissions: _permissions, role: _role }: { accessToken: string; callVolume: number; credentials: RealtimeRoomCredentials; onCallVolumeChange: (volume: number) => void; onSelfAccessChange: (access: { role: RoomRole; permissions: RoomPermission[] }) => void; participantId: string; permissions: RoomPermission[]; role: RoomRole }) {
  const [activePane, setActivePane] = useState<"chat" | "camera" | "members">("chat");
  const [draft, setDraft] = useState("");
  const [messages, setMessages] = useState<PreviewMessage[]>([]);
  const send = () => { const text = draft.trim(); if (!text) return; setMessages((current) => [...current, { id: `${Date.now()}`, authorName: "المضيف", text, mine: true }]); setDraft(""); };
  return <View style={styles.panel}><View style={styles.toolsRow}><Tool active={activePane === "chat"} icon="chat-bubble-outline" label="الدردشة" onPress={() => setActivePane("chat")} /><Tool icon="mic-none" label="اتصال صوتي" onPress={() => undefined} /><Tool active={activePane === "camera"} icon="videocam" label="اتصال كاميرا" onPress={() => setActivePane("camera")} /><Tool icon="radio" label="هوكي توكي" onPress={() => undefined} /><Tool active={activePane === "members"} icon="groups-2" label="الموجودون (1)" onPress={() => setActivePane("members")} /></View>{activePane === "chat" ? <View style={styles.chatPane}><View style={styles.chatHead}><Text style={styles.chatTitle}>الدردشة العامة</Text><MaterialIcons color="#C3CEE8" name="keyboard-arrow-down" size={22} /></View><FlatList contentContainerStyle={styles.messagesContent} data={messages} keyExtractor={(message) => message.id} renderItem={({ item }) => <Row item={item} onDelete={() => setMessages((current) => current.filter((message) => message.id !== item.id))} />} style={styles.messages} /><View style={styles.composer}><Pressable accessibilityLabel="إرسال" onPress={send} style={styles.send}><MaterialIcons color="#FFFFFF" name="send" size={25} /></Pressable><TextInput maxLength={800} onChangeText={setDraft} onSubmitEditing={send} placeholder="اكتب رسالتك…" placeholderTextColor="#7383AA" returnKeyType="send" style={styles.input} textAlign="right" value={draft} /><MaterialIcons color="#A4B0CC" name="sentiment-satisfied-alt" size={25} /></View></View> : null}{activePane === "camera" ? <View style={styles.emptyPane}><MaterialIcons color="#7D8CAD" name="videocam" size={36} /></View> : null}{activePane === "members" ? <View style={styles.memberPane}><View style={styles.memberRow}><View style={styles.avatar}><Text style={styles.avatarText}>م</Text></View><View style={styles.memberInfo}><Text style={styles.memberName}>المضيف</Text><Text style={styles.memberRole}>صلاحيات كاملة</Text></View><MaterialIcons color="#B49DFF" name="workspace-premium" size={21} /></View></View> : null}</View>;
}

function Tool({ active = false, icon, label, onPress }: { active?: boolean; icon: React.ComponentProps<typeof MaterialIcons>["name"]; label: string; onPress: () => void }) { return <Pressable accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [styles.tool, active && styles.toolActive, pressed && styles.pressed]}><MaterialIcons color="#DFE5F6" name={icon} size={27} /><Text style={styles.toolLabel}>{label}</Text></Pressable>; }
function Row({ item, onDelete }: { item: PreviewMessage; onDelete: () => void }) { return <View style={styles.messageRow}><View style={[styles.avatar, item.mine && styles.avatarMine]}><Text style={styles.avatarText}>{item.authorName.slice(0, 1)}</Text></View><View style={[styles.bubble, item.mine && styles.bubbleMine]}><View style={styles.messageHead}><Text style={styles.sender}>{item.authorName}</Text><Pressable accessibilityLabel="حذف الرسالة" onPress={onDelete}><MaterialIcons color="#A7B6D9" name="delete-outline" size={16} /></Pressable></View><Text style={styles.messageText}>{item.text}</Text></View></View>; }

const styles = StyleSheet.create({
  avatar: { alignItems: "center", backgroundColor: "#28517E", borderRadius: 21, height: 42, justifyContent: "center", width: 42 }, avatarMine: { backgroundColor: "#6846D6" }, avatarText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" }, bubble: { backgroundColor: "#1B2947", borderRadius: 14, flexShrink: 1, maxWidth: "82%", paddingHorizontal: 12, paddingVertical: 8 }, bubbleMine: { backgroundColor: "#3D2D78" },
  chatHead: { alignItems: "center", borderBottomColor: "#29364F", borderBottomWidth: 1, flexDirection: "row-reverse", paddingBottom: 8 }, chatPane: { backgroundColor: "#10192A", borderColor: "#2A3C5D", borderRadius: 18, borderWidth: 1, flex: 1, marginTop: 16, minHeight: 285, paddingHorizontal: 14, paddingTop: 13 }, chatTitle: { color: "#F2F4FF", fontSize: 15, fontWeight: "900" }, composer: { alignItems: "center", borderTopColor: "#28364E", borderTopWidth: 1, flexDirection: "row", gap: 8, marginHorizontal: -14, paddingHorizontal: 12, paddingVertical: 10 },
  emptyPane: { alignItems: "center", backgroundColor: "#10192A", borderColor: "#2A3C5D", borderRadius: 18, borderWidth: 1, flex: 1, justifyContent: "center", marginTop: 16, minHeight: 285 }, input: { backgroundColor: "#111C31", borderColor: "#2F405E", borderRadius: 14, borderWidth: 1, color: "#F8F8FF", flex: 1, fontSize: 14, height: 49, paddingHorizontal: 13 },
  memberInfo: { flex: 1, marginRight: 9 }, memberName: { color: "#F8F8FF", fontSize: 14, fontWeight: "800", textAlign: "right" }, memberPane: { backgroundColor: "#10192A", borderColor: "#2A3C5D", borderRadius: 18, borderWidth: 1, flex: 1, marginTop: 16, minHeight: 285, padding: 12 }, memberRole: { color: "#98A4C0", fontSize: 11, marginTop: 2, textAlign: "right" }, memberRow: { alignItems: "center", flexDirection: "row-reverse", minHeight: 60 },
  messageHead: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between" }, messageRow: { alignItems: "flex-start", flexDirection: "row-reverse", gap: 9, marginBottom: 12 }, messageText: { color: "#F8F8FF", fontSize: 14, lineHeight: 21, marginTop: 3, textAlign: "right" }, messages: { flex: 1 }, messagesContent: { flexGrow: 1, paddingTop: 9 }, panel: { flex: 1, marginHorizontal: 8, paddingTop: 16 }, pressed: { opacity: 0.76, transform: [{ scale: 0.97 }] }, sender: { color: "#AE91FF", fontSize: 12, fontWeight: "900" }, send: { alignItems: "center", backgroundColor: "#6F43D5", borderRadius: 15, height: 49, justifyContent: "center", width: 54 },
  tool: { alignItems: "center", borderColor: "#283750", borderLeftWidth: 1, flex: 1, gap: 7, justifyContent: "center", minHeight: 105, paddingHorizontal: 3, paddingVertical: 10 }, toolActive: { backgroundColor: "#241C50", borderBottomColor: "#8D63FF", borderBottomWidth: 3 }, toolLabel: { color: "#D3DAEF", fontSize: 11, fontWeight: "800", textAlign: "center" }, toolsRow: { backgroundColor: "#111A2B", borderColor: "#253653", borderRadius: 18, borderWidth: 1, flexDirection: "row-reverse", overflow: "hidden" },
});
